apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: mustakmbstuakscluster 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mustakmbstuakscluster 
    spec:
      containers:
        - name: mustakmbstuakscluster 
          image: myappacr.azurecr.io/mustakmbstuakscluster
          ports:
          - containerPort: 8080